// import Inter from 'next/font/google'; // Assurez-vous de fournir le chemin correct vers le fichier contenant la fonction Inter

import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={className}>{children}</body> */}
      <body >{children}</body>

    </html>
  );
}


